os:
- osx
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
- git submodule update --init --recursive
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
notifications:
  slack: toshi0383:rQxydx8brjMrnkFQRgQHcJ2V
install:
script:
- ./script/test.sh
- exit $?
